---
# tasks file for roles/webserver

- name: Upload the application file
  copy:
    src: ../files/index.php
    dest: "{{path_to_app}}"
    mode: 0755
  tags: upload

- name: Host Info on page
  copy:
    dest: "{{path_to_app}}/info.php"
    content: <h1> Info on your website IP address {{ansible_hostname}} Tahoo </h1>

          
- name: See directory contents
  command: ls -la {{ path_to_app }}
  register: dir_contents

- name: Debug directory contents
  debug:
    msg: "{{ dir_contents }}"

- name: Configure PHP.ini file
  lineinfile:
    path: /etc/php.ini
    regexp: ^short_open_tag
    line: 'short_open_tag=on'
  notify: Restart Apache
      